[project]
name = "wordle-benchmark"
version = "0.1.0"
description = "Testing LLM performance with Wordle"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "requests>=2.32.3",
]
